musicapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

end

musicapp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
validates :title, :band_id, :year, :live, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Track
end

musicapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

musicapp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album

  has_many :tracks,
    through: :albums,
    source: :tracks 
end

musicapp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  album_id   :integer          not null
#  ord        :integer          not null
#  regular    :boolean          default(TRUE), not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
validates :title, :album_id, :ord, :regular, presence: true

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Album

  has_one :band,
    through: :album,
    source: :band
end

musicapp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credientials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil 
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(pw)
    bcrypt = BCrypt::Password.new(self.password_digest)
    bcrypt.is_password?(pw)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end


end

musicapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    render :new
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :year, :live)
  end
end

musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  
  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_logged_in
    redirect_to bands_url if logged_in?
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end
end

musicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    band = Band.find_by(id: params[:id])
    band.delete
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
    render :new
  end

  def create
    # debugger
    user = User.find_by_credientials(params[:user][:email], params[:user][:password])
    if user
      log_in_user!(user)
      redirect_to bands_url
    else
      flash.now[:errors] = ['Crediential cannot be found!']
      render :new
    end

  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

musicapp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
    render :new
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:title, :album_id, :ord, :regular, :lyrics)
  end
end

musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

musicapp/app/helpers/application_helper.rb
module ApplicationHelper
end

musicapp/app/views/albums/_form.html.erb
<% if action == :edit %>
  <% action_url = album_url(album) %>
<% else %>
  <% action_url = albums_url %>
<% end %>

<form action="<%= action_url %>" method="post">
<% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
<% end %>
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

<label for="title">Title</label>
<input id="title" type="text" name="album[title]" value="<%= album.title %>">
<br>
<label for="year">Year</label>
<input id="year" type="text" name="album[year]" value="<%= album.year %>">
<br>

<label for="live">Live</label>
  <input type="radio" name="album[live]" value="LIVE" id="live" <%= "checked" if album.live %>>
<label for="studio">Studio</label>
  <input type="radio" name="album[live]" value="STUDIO" id="studio" <%= "checked" if !album.live %>>

  <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
    <% Band.all.each do |band| %>
      <option <%= "selected" if album.band_id == band.id %> value="<%= band.id %>"> <%= band.name %></option>
    <% end %>
    </select>


  <input type="submit" name="" value="Submit!">
</form>

musicapp/app/views/albums/edit.html.erb
<h1 class='page-header'>Edit <%= @album.title %></h1>

<%= render "form", album: @album, action: :edit %>
<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="delete">

</form>

musicapp/app/views/albums/new.html.erb
<h1>New album</h1>
<%= render "form", album: @album, action: :new%>

musicapp/app/views/albums/show.html.erb
<h1>Show album</h1>

<h2> <%= @album.title %> </h2>
<br>
<a href= "<%= band_url(@album.band_id) %>" >Return</a>
<a href=" <%= edit_album_url(@album) %> ">edit</a>
<br>
<br>
<br>
<br>
<br>
<br>
<ul>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
  <% end %>
</ul>

<a href=" <%= new_album_track_url(@album) %> ">new track</a>

musicapp/app/views/bands/_form.html.erb
<% if action == :edit %>
  <% action_url = band_url(band) %>
<% else %>
  <% action_url = bands_url %>
<% end %>


<form action=  '<%= action_url %>' method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
  <input id="name" type="text" name="band[name]" value="<%= band.name %>">

  <input type="submit" value= "<%= action == :edit ? 'Edit Band' : 'Add Band'%>">

</form>

musicapp/app/views/bands/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band, action: :edit %>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="delete">

</form>

musicapp/app/views/bands/index.html.erb
<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>


<br>
<br>
<br>
<br>

<ul>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>

musicapp/app/views/bands/new.html.erb
<h1>New band</h1>
<%= render "form", band: @band, action: :new%>

musicapp/app/views/bands/show.html.erb
<h1>Show band</h1>

<h2> <%= @band.name %> </h2>
<br>
<a href= "<%= bands_url %>" >Return</a>
<a href=" <%= edit_band_url(@band) %> ">edit</a>

<br>
<br>
<br>
<br>
<br>
<br>
<ul>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.title %></a></li>
  <% end %>
</ul>

<a href=" <%= new_band_album_url(@band) %> ">Add an album</a>

musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
 <h1> <%= current_user.email %> </h1>
 <form action="<%= session_url %>" method="post">
   <input type="hidden" name="_method" value="DELETE">
   <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   <input type="submit" name="" value="Log Out">
 </form>
   <% end %>
    <%= yield %>
  </body>
</html>

musicapp/app/views/tracks/_form.html.erb
<% if action == :edit %>
  <% action_url = track_url(track) %>
<% else %>
  <% action_url = tracks_url %>
<% end %>

<form action="<%= action_url %>" method="post">
<% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
<% end %>
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

<label for="title">Title</label>
<input id="title" type="text" name="track[title]" value="<%= track.title %>">
<br>
<label for="ord">Ord</label>
<input id="ord" type="text" name="track[ord]" value="<%= track.ord %>">
<br>

<label for="regular">Regular</label>
  <input type="radio" name="track[regular]" value="REGULAR" id="regular" <%= "checked" if track.regular %>>
<label for="bonus">Bonus</label>
  <input type="radio" name="track[regular]" value="BONUS" id="bonus" <%= "checked" if !track.regular %>>

  <label for='track-album'>Album</label>
    <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option <%= "selected" if track.album_id == album.id %> value="<%= album.id %>"> <%= album.title %></option>
    <% end %>
    </select>


  <input type="submit" name="" value="Submit!">
</form>

musicapp/app/views/tracks/edit.html.erb
<h1 class='page-header'>Edit <%= @track.title %></h1>

<%= render "form", track: @track, action: :edit %>
<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="delete">

</form>

musicapp/app/views/tracks/new.html.erb
<h1>New track</h1>
<%= render "form", track: @track, action: :new%>

musicapp/app/views/tracks/show.html.erb
<h1>Show track</h1>

<h2> <%= @track.title %> </h2>
<br>
<a href= "<%= album_url(@track.album_id) %>" >Return</a>
<a href=" <%= edit_track_url(@track) %> ">edit</a>

musicapp/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for='new-user-email'>Email</label>
  <input id='new-user-email' type="text" name="user[email]">
  <br>
  <label for='new-user-password'>Password</label>
  <input id='new-user-password' type="password" name="user[password]">
  <br>
  <input type="submit" value = "Submit">
</form>

musicapp/app/views/users/show.html.erb
<h1 class='page-header'>Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>